# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:               Code As Manuscript
tagline:             'Change the way you see your code.'
description:         'Writing your code and analyses as if <i>it</i> was the manuscript.'
url:                 http://codeasmanuscript.github.io/workshops
baseurl: /workshops/

author:
  name:           'Daiva & Luke'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/codeasmanuscript
